storageClasses:
  StructuredDataDict:
    pytype: dict
  StructuredDataList:
    pytype: list
  TablePersistable:
    pytype: lsst.afw.table.io.Persistable
  Wcs:
    pytype: lsst.afw.geom.skyWcs.SkyWcs
  Psf:
    pytype: lsst.afw.detection.Psf
  CoaddInputs:
    pytype: lsst.afw.image.CoaddInputs
  VisitInfo:
    pytype: lsst.afw.image.VisitInfo
  ApCorr:
    pytype: lsst.afw.image.ApCorrMap
  PhotoCalib:
    pytype: lsst.afw.image.PhotoCalib
  TransmissionCurve:
    pytype: lsst.afw.image.TransmissionCurve
  Camera:
    pytype: lsst.afw.cameraGeom.Camera
  Detector:
    pytype: lsst.afw.cameraGeom.Detector
  Box2I:
    pytype: lsst.geom.Box2I
  Extent2I:
    pytype: lsst.geom.Extent2I
  Point2I:
    pytype: lsst.geom.Point2I
  Image: &Image
    pytype: lsst.afw.image.Image
    delegate: lsst.obs.base.exposureAssembler.ExposureAssembler
    parameters:
      - bbox
      - origin
  ImageF:
    inheritsFrom: Image
    pytype: lsst.afw.image.ImageF
  ImageI:
    inheritsFrom: Image
    pytype: lsst.afw.image.ImageI
  ImageU:
    inheritsFrom: Image
    pytype: lsst.afw.image.ImageU
  DecoratedImage:
    pytype: lsst.afw.image.DecoratedImage
  DecoratedImageU:
    inheritsFrom: DecoratedImage
    pytype: lsst.afw.image.DecoratedImageU
  Mask:
    pytype: lsst.afw.image.Mask
    delegate: lsst.obs.base.exposureAssembler.ExposureAssembler
    parameters:
      - bbox
      - origin
  MaskX:
    inheritsFrom: Mask
    pytype: lsst.afw.image.MaskX
  MaskedImage:
    pytype: lsst.afw.image.MaskedImage
  MaskedImageF:
    inheritsFrom: MaskedImage
    pytype: lsst.afw.image.MaskedImageF
  MaskedImageU:
    inheritsFrom: MaskedImage
    pytype: lsst.afw.image.MaskedImageU
  MaskedImageI:
    inheritsFrom: MaskedImage
    pytype: lsst.afw.image.MaskedImageI
  Catalog:
    pytype: lsst.afw.table.BaseCatalog
  PeakCatalog:
    pytype: lsst.afw.detection.PeakCatalog
  Polygon:
    pytype: lsst.afw.geom.Polygon
  SimpleCatalog:
    pytype: lsst.afw.table.SimpleCatalog
  SourceCatalog:
    pytype: lsst.afw.table.SourceCatalog
  ObjectMaskCatalog:
    pytype: lsst.pipe.tasks.objectMasks.ObjectMaskCatalog
  ExposureCatalog:
    pytype: lsst.afw.table.ExposureCatalog
  DataFrame:
    pytype: pandas.DataFrame
    components:
      columns: DataFrameIndex
    parameters:
      - columns
  DataFrameIndex:
    pytype: pandas.Index
  SkyMap:
    pytype: lsst.skymap.BaseSkyMap
  PropertySet:
    pytype: lsst.daf.base.PropertySet
  PropertyList:
    pytype: lsst.daf.base.PropertyList
  Defects:
    pytype: lsst.ip.isr.Defects
  QECurve:
    pytype: lsst.meas.algorithms.Curve
  CrosstalkCalib:
    pytype: lsst.ip.isr.CrosstalkCalib
  Linearizer:
    pytype: lsst.ip.isr.Linearizer
  PhotonTransferCurveDataset:
    pytype: lsst.ip.isr.PhotonTransferCurveDataset
  # TODO: remove Filter in DM-27177
  Filter:
    pytype: lsst.afw.image.Filter
  FilterLabel:
    pytype: lsst.afw.image.FilterLabel
    # To support exposure.filter; remove in DM-27177
    delegate: lsst.obs.base.formatters.filter.FilterTranslator
  Exposure:
    pytype: lsst.afw.image.Exposure
    delegate: lsst.obs.base.exposureAssembler.ExposureAssembler
    parameters:
      - bbox
      - origin
    components:
      image: Image
      mask: Mask
      variance: Image
      wcs: Wcs
      psf: Psf
      photoCalib: PhotoCalib
      visitInfo: VisitInfo
      apCorrMap: ApCorr
      coaddInputs: CoaddInputs
      transmissionCurve: TransmissionCurve
      metadata: PropertyList
      # TODO: for consistency with Exposure.getFilterLabel(). Deprecate in DM-27177, remove in DM-27811.
      filterLabel: FilterLabel
      detector: Detector
      validPolygon: Polygon
    derivedComponents:
      bbox: Box2I
      dimensions: Extent2I
      xy0: Point2I
      # TODO: change filter to FilterLabel and make non-derived in DM-27177. This is a breaking change.
      filter: Filter
  ExposureF:
    inheritsFrom: Exposure
    pytype: lsst.afw.image.ExposureF
    components:
      image: ImageF
      mask: MaskX
      variance: ImageF
  ExposureI:
    inheritsFrom: Exposure
    pytype: lsst.afw.image.ExposureI
    components:
      image: ImageI
      mask: MaskX
      variance: ImageF
  ExposureU:
    inheritsFrom: Exposure
    pytype: lsst.afw.image.ExposureU
    components:
      image: ImageU
      mask: MaskX
      variance: ImageF
  Background:
    pytype: lsst.afw.math.BackgroundList
  Config:
    pytype: lsst.pex.config.Config
  Packages:
    pytype: lsst.base.Packages
  NumpyArray:
    pytype: numpy.ndarray
  StrayLightData:
    pytype: lsst.ip.isr.StrayLightData
  BrighterFatterKernel:
    pytype: lsst.cp.pipe.makeBrighterFatterKernel.BrighterFatterKernel
  Thumbnail:
    pytype: numpy.ndarray
  Plot:
    pytype: matplotlib.figure.Figure
  MetricValue:
    pytype: lsst.verify.Measurement
  Stamps:
    pytype: lsst.meas.algorithms.Stamps
  BrightStarStamps:
    pytype: lsst.meas.algorithms.brightStarStamps.BrightStarStamps
  AstropyTable:
    pytype: astropy.table.Table
  AstropyQTable:
    pytype: astropy.table.QTable
